<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\ci_concept.png" />
    <None Remove="Images\ship_icon.png" />
    <None Remove="Images\splash.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\ci_concept.png" />
    <Resource Include="Images\ship_icon.png" />
    <Resource Include="Images\splash.png" />
  </ItemGroup>

</Project>
